
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
flyway:
  table: flyway_schema_version
  enabled: false
logging:
  level:
    org.hibernate: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    root: debug


